Portable text
pokornyd/rich-text-resolver pull request #3
Opened 2023-03-16 09:56 UTC by pokornyd

### Motivation

This PR introduces portable text support to the rich text parser. Still a work in progress, portable text is currently only supported in RichTextNodeParser. Code base is going to be refactored and functionality extended to RichTextBrowserParser in later iterations. Draft PR created to provide an option to test and review existing functionality.

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

Instantiate a RichTextNodeParser class, use the parse method on a piece of rich text from Kontent.ai. Try creating obscure edge cases to identify potential issues with the parsing logic. Check existing portable text tests for usage details.

2023-04-11 08:11 UTC, JiriLojda requested changes
Good job with using the FP structure, it looks great. 👍 Refactoring the algorithm to a single recursion through the tree might improve readability and performance. I would also unify the file names as right now there are at least two different naming conventions without an apparent pattern.

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +export const transform = (parsedTree: IOutputResult): IPortableTextItem[] => {
The two-part process seems too complicated. Why do you get rid of the tree structure (flatten it) before building the portable text? You give up useful information that you need to replace with different additional properties (e.g. child count) and then the building of the portable text from the flat structure seems rather complicated. I believe, that a simple recursive algorithm should be able to deal with all of this. It might look something like this (pseudo code).
```ts
const transform = (elements) => elements.flatMap(el => {
  switch(el._type) {
    case 'table':
      return transformTable(el, emptyState);
    case 'p':
      return transformBlock(el, emptyState);
    default:
      throw new Error('Invalid top-level element');
  }
})
const transformTable = (el, state) => {
  const rows = el.children.reduce(transformRow, state);
  const table = createTable(..., rows);
  return { elements: [table], state: state };
};
const transformLink = (el, state) => {
  const mark = createMark(...);
  const markDef = createLink(...);
  return { elements: [], state: { ...state, marks: [...state.marks, mark], markDefs: [...state.markDefs, markdDef]}};
};
const transformSpan = (el, state) => {
  const span = createSpan(..., state.marks);
  return { elements: [span], state: { ...state, marks: [] } };
};
const transformBlock = (el, state) => {
  const { elements: spans, state: newState } = el.children.reduce(transform, state);
  const block = createBlock(..., spans, newState.markdDefs);
  return { elements: [block], state: { ...newState, spans: [], markDefs: [] }};
};
```

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +    let links: string[] = [];
You can add these two into the accumulator of the `reduce` bellow.

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +export const mergeSpansAndMarks = (itemsToMerge: IPortableTextItem[]): IPortableTextItem[] => {
Why is this function exported?

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +                const lastBlockIndex = findLastIndex(mergedItems, item => item._type === 'block');
You don't need this utility. You don't care about the index of the last block, a reference to it would be enough because this is the only thing you use the index for. In this case, the built-in function `mergedItems.findLast` should be the proper tool.

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +    return nodes.reduce((finishedItems: IPortableTextItem[], node: IDomNode) => {
You can rewrite this to use `flatMap` instead of the `reduce` function quite easily. I think using more specialized tools is better.

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +        let currentListType = listType;
You can replace all of these `let` declarations with `const`s quite easily. Refactoring the calculation of `currentListType` into a separate function might help with that.

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +    default: (node: IDomHtmlNode) => {
When there is a transformer missing (i.e. using the default transformer), does it mean a mistake? It would mean the tag will be completely excluded from the portable text representation, right? If we consider this to be a mistake, I would prefer to throw an error instead of ignoring it with a log. If we think this is something useful (consciously ignoring some tags) then I would not log anything since it might be pretty spammy for bigger values with lots of those tags. What do you think?

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +    ...ignoredElements.reduce(
Using `Object.fromEntries(tags.map(t => [t, myTransformer] as const)` might be more readable than the reduce (and as an insignificant bonus changes the complexity from quadratic to linear 🙂)

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +const ignoreElement: TransformElementFunction = (node: IDomHtmlNode) => [];
You don't need to specify the `node` argument if you don't use it. :)

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +const transformListItem: TransformListItemFunction = (node: IDomHtmlNode, depth: number, listType: ListType): IPortableTextListBlock[] =>
If you don't use an argument that is not the last argument of the function, you can name it `_` and TypeScript will stop warning about and unused variable.

2023-04-11 08:11 UTC, JiriLojda commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +    'table': transformTable,
In our rich text, tables always contain only the `tbody` element? 
![image](https://user-images.githubusercontent.com/25480503/230436050-984f117e-94fd-4d92-a0aa-a76db9e182d9.png)

2023-04-11 08:11 UTC, JiriLojda commented on src/utils/browser-parser-utils.ts
> +export type OmitKey<T, K> = Pick<T, Exclude<keyof T, K>>;
There is a built-in type for this. `Omit` 😄

2023-04-11 08:11 UTC, JiriLojda commented on test/rich-text-to-json-converter.spec.ts
>  const dummyRichText: Elements.RichTextElement = {
I don't see much value in this constant. You only use the `value` property and assign it in almost all test cases. You can simply use the strings you assign directly.

2023-04-11 08:11 UTC, JiriLojda commented on test/rich-text-to-json-converter.spec.ts
> +  it("resolves a table", () => {
Missing implementation 😛

2023-04-11 08:11 UTC, JiriLojda commented on package.json
> +    "@sanity/block-tools": "^3.5.0",
Do you use this? I can't find any import using this package.

2023-04-11 08:44 UTC, Simply007 commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +export const transform = (parsedTree: IOutputResult): IPortableTextItem[] => {
Could be split out to separate issue since it does not affect public API.

2023-04-12 10:17 UTC, pokornyd commented on src/utils/browser-parser-utils.ts
> +export type OmitKey<T, K> = Pick<T, Exclude<keyof T, K>>;
I prefer the hard way! :D this is a leftover from earlier iterations and wasn't really used anyway. removed it altogether

2023-04-12 10:18 UTC, pokornyd commented on package.json
> +    "@sanity/block-tools": "^3.5.0",
nope, again, was used in earlier iterations and forgotten about. removed

2023-04-12 10:43 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +                const lastBlockIndex = findLastIndex(mergedItems, item => item._type === 'block');
for some reason, findLast method is not available for arrays in this project, despite using 5.0.3 version of typescript and target esnext in tsconfig. will move this to a separate issue

2023-04-12 10:45 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +export const mergeSpansAndMarks = (itemsToMerge: IPortableTextItem[]): IPortableTextItem[] => {
isn't anymore :)

2023-04-12 10:49 UTC, pokornyd commented on test/rich-text-to-json-converter.spec.ts
>  const dummyRichText: Elements.RichTextElement = {
I assume you mean the dummyRichText, rather than the highlighted mock? this is also leftover from previous iterations, which worked with the SDK element as a whole. as this is no longer the case, it can be deleted and a simple string variable used instead. will fix it

2023-04-12 11:03 UTC, pokornyd commented on test/rich-text-to-json-converter.spec.ts
> +  it("resolves a table", () => {
not anymore!

2023-04-14 11:06 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +export const transform = (parsedTree: IOutputResult): IPortableTextItem[] => {
https://github.com/pokornyd/rich-text-resolver/issues/11

2023-04-14 11:17 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +    default: (node: IDomHtmlNode) => {
I agree that it's preferable to throw an error. Ignoring the tag has the unwanted outcome of subsequent nested spans or blocks being processed anyway, which may result in unexpected issues during the composition process.

2023-04-14 12:33 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +                const lastBlockIndex = findLastIndex(mergedItems, item => item._type === 'block');
submitted as issue: https://github.com/pokornyd/rich-text-resolver/issues/12

2023-04-14 12:42 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +    return nodes.reduce((finishedItems: IPortableTextItem[], node: IDomNode) => {
agreed, rewritten

2023-04-14 13:05 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +    let links: string[] = [];
I'll address this as a part of https://github.com/pokornyd/rich-text-resolver/issues/11

2023-04-14 13:06 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +        let currentListType = listType;
likewise, will be adressed in https://github.com/pokornyd/rich-text-resolver/issues/11 which will ideally render the flatten function obsolete

2023-04-14 13:12 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +    ...ignoredElements.reduce(
rewritten

2023-04-14 13:12 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +const ignoreElement: TransformElementFunction = (node: IDomHtmlNode) => [];
oversight, removed :)

2023-04-14 13:16 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +    'table': transformTable,
It would appear so. Our tables don't really allow any customization apart from formatting the cell contents themselves.

2023-04-14 13:16 UTC, pokornyd commented on src/transformers/portable_text_transformer/PortableTextTransformer.ts
> +const transformListItem: TransformListItemFunction = (node: IDomHtmlNode, depth: number, listType: ListType): IPortableTextListBlock[] =>
thanks, replaced the unused argument :)

2023-04-17 13:18 UTC, merged